services:
  postgres:
    image: "postgres:${PG_VERSION}"
    container_name: ${DB_NAME}
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql
      - ./../sql/init.sql:/docker-entrypoint-initdb.d/init.sql:z
    networks:
      - postgres_network

  pgadmin:
    image: "dpage/pgadmin4:${PGADMIN_VERSION}"
    container_name: pgadmin
    volumes:
      - pgadmin_working_dir:/var/lib/pgadmin
      - pgadmin_config_dir:/pgadmin4
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASSWORD}
    depends_on:
      - postgres
    ports:
      - "5433:80"
    networks:
      - postgres_network

volumes:
  postgresql_data:
    driver: local
  pgadmin_working_dir:
    driver: local
  pgadmin_config_dir:
    driver: local

networks:
  postgres_network:
    driver: bridge
